### ISSUE TITLE
handle m3u8

### ISSUE THREAD

**Issue by simonckenyon** [andy-portmen/open-in-vlc#11]
I have a set top box which provides a web interface.
There are links on the page with URLs like:

http://<snip>/stream.m3u?ref=1:0:19:835:3EA:2174:EEEE0000:0:0:0:&name=RT%C3%89%20One&fname=RT%C3%89%20One

When i click on the links it saves a file with an extension of m3u8.

Using wget I can see that the server returns a content type of application/x-mpegurl

Would it be possible to be able to open this with your extension?

**Comment by andy-portmen** [comment]
> When i click on the links it saves a file with an extension of m3u8.

When there are more than one audio/video links on a webpage, the extension combines them in a m3u8 container. VLC reads the file and insert all the links to the playlist.

This doesnt work for you?
