### ISSUE TITLE
Open using flatpak vlc?

### ISSUE THREAD

**Issue by pvreevil** [andy-portmen/open-in-vlc#12]

**Comment by andy-portmen** [comment]
Is there a terminal command to access this flatpak VLC?

**Comment by pvreevil** [comment]
> flatpak run org.videolan.VLC

**Comment by andy-portmen** [comment]
pack the command in a batch script and insert the path of this script as the path of VLC on the options page

**Comment by pvreevil** [comment]
well, since i am running linux(FedoraSilverblue31) ive created the following bash script.

```
#!/bin/bash
flatpak run org.videolan.VLC
```
PATH to VLC executable /var/home/erika/vlc.sh

It didn't work, just open an empty vlc.

**Comment by pvreevil** [comment]
Maybe it could work by adding flatpak binary to PATH, and using arguments(`run org.videolan.VLC`) .

Although i understand if u dont wanna support this

**Comment by pvreevil** [comment]
```
#!/bin/bash
flatpak run org.videolan.VLC "$@"
```
worked
