### ISSUE TITLE
Feature request: save URL to file

### ISSUE THREAD

**Issue by mrwm** [andy-portmen/open-in-vlc#21]
Sometimes, some sites split up videos to multiple segments and opening them one by one would be a hassle. [Here's an example of a video split to multiple segments](https://www.jwplayer.com/developers/web-player-demos/adaptive-streaming/). 

It would be awesome if it's possible to save the list into a m3u8 (or text) file and open it via VLC instead of opening a new URL every 3/5 seconds.

**Comment by andy-portmen** [comment]
This extension suggests the "M3U8" link if it is available. For instance, for the example page take a look at the panel:

<img width="448" alt="Screen Shot 2021-01-13 at 13 43 14" src="https://user-images.githubusercontent.com/6779535/104454338-feef6a00-55a5-11eb-85ec-7cb7e99fa952.png">


Also note that if you send multiple links to the player, the extension creates a temporary M3U8 metadata file, and then passes it to the player.

**Comment by mrwm** [comment]
Ok, I see it. I'll close this issue then.
