### ISSUE TITLE
ConnectNative pass link variable to the local script

### ISSUE THREAD

**Issue by diskxo** [andy-portmen/open-in-vlc#25]
Hi, I have a question I would like to ask you, as I am developing a similar extension to yours. How do you pass variables from the chrome extension with Connect Native to the local javascript file? I tried to look at the extension code but I don't understand how it works. Can you help me? Thanks: D

**Comment by andy-portmen** [comment]
I am not sure what you are trying to do. 

Take a look at https://github.com/andy-portmen/open-in-vlc/blob/master/firefox/common.js#L22
