### ISSUE TITLE
[Request] Please make similar Chrome extension for MPC-HC

### ISSUE THREAD

**Issue by Alp1821** [andy-portmen/open-in-vlc#30]
Actually I found similar extension like yours, but that is not maintained anymore.
https://chrome.google.com/webstore/detail/send-to-vlc-videolan-medi/hfckgfbhdacemicpjljhfbjmkiggeche
https://github.com/belaviyo/send-to-vlc

In this extension if I change application path _(like: "C:\Program Files\MPC-HC\mpc-hc64.exe")_ in option it actually works for other players.
But in your extension if I do the same it doesn't work for other players.

So my request is to take code from that project (https://github.com/belaviyo/send-to-vlc) and make a separate extension for MPC-HC. It will be like **Open in MPC-HC**.
Please sir...

**Comment by andy-portmen** [comment]
I just checked the extension with a custom application, and it works as expected. Double-check the executable path and retry.

What are your browser and OS?

**Comment by Alp1821** [comment]
Chrome
Windows 10 21h2


> I just checked the extension with a custom application

Which extension? Yours? Or belaviyo's?

**Comment by andy-portmen** [comment]
> Which extension?

Mine

**Comment by Alp1821** [comment]
No that's not working. Even though it works, it is not my request to you.

https://addons.opera.com/en/extensions/details/send-to-media-player-classic-mpc-hc/
I'm requesting for this kind of thing for chrome.

Don't know why that person removed his extension for other players from chrome web store. But they are available on Firefox and Opera.

Please make a chrome extension named Open in MPC like him.

**Comment by Alp1821** [comment]
> Mine

Yes it is working with MPC
"C:\Program Files\MPC-HC\mpc-hc64.exe"        - **Doesn't work**
C:\Program Files\MPC-HC\mpc-hc64.exe           - **Works**

Inverted commas are culprits.

So everything is working. Only need to change the name to Open in MPC, and the logo.
Please sir make a chrome extension.

**Comment by andy-portmen** [comment]
It is very unlikely that I submit and maintain a new extension. There are many video players out there, and we cannot support all of them. You can download the GT project to a local directory and edit the title in the `manifest.json` file. For icons, replace the ones in the `data/icons` directory. That's it.

**Comment by andy-portmen** [comment]
> And fix one bug. Right click menu not working.

For the right-click to appear, the link need to have a valid extension `.mp4` instead of `_mp4`

**Comment by Alp1821** [comment]
> It is very unlikely that I submit and maintain a new extension. There are many video players out there, and we cannot support all of them. You can download the GT project to a local directory and edit the title in the `manifest.json` file. For icons, replace the ones in the `data/icons` directory. That's it.

I don't know how to do those things. 😥
But I'm sure that it is not a big headache for you to create another extension, because everything is already implemented.

Still if You really don't want to make different extensions for different players, You can do one thing. Rename your current extension to Open in External Player. Use a generic icon instead of VLC, MPC icons. No need of different icons basically. Inside settings people will set application path as per their need.

This looks so odd that I'm clicking on open in vlc, and it is launching a different player.

**Comment by Alp1821** [comment]
> For the right-click to appear, the link need to have a valid extension `.mp4` instead of `_mp4`

You can fix this in your code. Because belaviyo's one works well in right click menu. Code can be copied from there.

**Comment by Alp1821** [comment]
Will you make those two changes (Name and Icon)? If not then close this.
