### ISSUE TITLE
.

### ISSUE THREAD

**Issue by linlinxza** [andy-portmen/open-in-vlc#31]
.

**Comment by Bazooka69** [comment]
https://github.com/andy-portmen/open-in-vlc/issues/31#issue-1233352764 #32
![0b956909431cd1fb95d04ec47d1a22a5 18](https://user-images.githubusercontent.com/40459007/173245416-76771396-141a-4ef0-a914-a68d822e2a1a.jpg)

**Comment by linlinxza** [comment]
What is this? Seriously?

https://user-images.githubusercontent.com/40459007/173245416-76771396-141a-4ef0-a914-a68d822e2a1a.jpg
