### ISSUE TITLE
Cant use unzipped version

### ISSUE THREAD

**Issue by Kamiikaze** [andy-portmen/open-in-vlc#37]
I try to debug why the page title isnt used for m3u8 videos on the page I am using it (Vidoza)
But when downloading the repo und loading V3 as unzipped extension in chrome, the extensive cant communicate with the native client. No matter how often I reinstall the nativ and the extension.
The extension-console giving me following error:
`Unchecked runtime.lastError: Access to the specified native messaging host is forbidden.`

How can I use the extension localy to debug and add additional featues?

**Comment by andy-portmen** [comment]
[Download](https://github.com/andy-portmen/native-client/releases) the native client and add the id of the temporary extension to the list ([config.js](https://github.com/andy-portmen/native-client/blob/master/config.js)), then reinstall it.

**Comment by Kamiikaze** [comment]
> [Download](https://github.com/andy-portmen/native-client/releases) the native client and add the id of the temporary extension to the list ([config.js](https://github.com/andy-portmen/native-client/blob/master/config.js)), then reinstall it.

It worked, thanks!
Now I debugged the page and figured out it doesnt even get there where the page-title function will be used.

Stream-Location: `https://matriculant401merited.com/e/a2xzxr82s11g`
Media-Link: `https://delivery-node-bahiyy.voe-network.net/engine/hls2/01/08648/a2xzxr82s11g_n/master.**m3u8**?t=vEBnhDlbxdlcU6_oNtZM_4_yiHIQxKRNjW_zKA-ECb0&s=1678627238&e=14400&f=43240205&node=delivery-node-bahiyy.voe-network.net&i=83.135&sp=4500&asn=8881`

This is the only media link on the page so this code will be triggered
```
        if (links.length === 1) {
          const native = new Native(tab.id);
          open(links[0], native);
        }
```
and
`native.exec(prefs.path, [url]);`

But the link doesnt go through the `toM3U8` function where the title gets added.

**Comment by Kamiikaze** [comment]
I also tried to disable the "M3U8 Container" Option in the extension

**Comment by andy-portmen** [comment]
Creating a temp M3U8 file is unnecessary when there's only one link available. Instead, the link can be sent directly using the extension. A recent update allows the page title to be sent to VLC using the ":meta-title" argument. Please test it out and let me know if it works for you.

**Comment by Kamiikaze** [comment]
Works like a charm, thank you!

![image](https://user-images.githubusercontent.com/13954000/224678249-686caf5a-5997-4298-990b-5078d064b670.png)

**Comment by Kamiikaze** [comment]
P.S.: Maybe you could add this info to the readme, so its easier for others to contribute/debug by their own :)

> [Download](https://github.com/andy-portmen/native-client/releases) the native client and add the id of the temporary extension to the list ([config.js](https://github.com/andy-portmen/native-client/blob/master/config.js)), then reinstall it.
