### ISSUE TITLE
Background ?

### ISSUE THREAD

**Issue by trimechee** [andy-portmen/open-in-vlc#49]
Hello, a developer said about Native client: "..... it requires running separate nodejs client in the background performing as a man in the middle https://github.com/andy-portmen/native-client this is a 30MB full embedded chrome running all the time :( "

so I have a few questions please:

by reading the changelog of a previous version of native client, I discover that we are supposed to install nodejs: "It is recommended to have NodeJS installed on your system to use the NodeJS-based native clients (windows.zip, linux.zip , and mac.zip)."

so our beloved Open-in-vlc does not work 100% if nodejs is not installed? native client is not enough? do we have to install native client and nodejs at the same time? I tried to install nodejs but nodejs tells me nodejs is no longer compatible with windows 7 os unfortunately.....

My second question please, is this true native client, or nodejs will remain permanently active in the background even when you close the web browser or vlc player? I ask the question because my laptop is old and weak and manufactured in 2012 so I have to save resources and avoid background processes.....

Thank you so much !

**Comment by andy-portmen** [comment]
> do you advise me to install NodeJS v13.14.0 for windows 7

No, just use the included NodeJS. There's no need to update NodeJS for this project. It only uses it for one second to open the native application, and that's all.
